/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view.paneles;

import com.conexion.Conectar;
import com.mysql.jdbc.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author gemma
 */
public class pnlCinco extends javax.swing.JPanel {

    /**
     * Creates new form pnlUno
     */
    public pnlCinco() {
        initComponents();
        arr[0] = new int[]{1,2};
        arr[1] = new int[]{3,4};
        arr[2] = new int[]{5,6,7,8,9,10};
        arr[3] = new int[]{11,12};
        arr[4] = new int[]{13,14,15,16,17,18};
        arr[5] = new int[]{19,20};
        arr[6] = new int[]{21,22,23,24,25,26,27,28,29,30};
        arr[7] = new int[]{31,32,33,34,35,36};
        arr[8] = new int[]{37,38};
        arr[9] = new int[]{39,40,41,42,43,44,45,46,47,48};
        arr[10] = new int[]{49,50,51,52,53,54};
        arr[11] = new int[]{55,56};
        arr[12] = new int[]{57,58,59,60,61,62,63,64,65,66,67,68,69,70};
        arr[13] = new int[]{71,72,73,74,75,76,77,78,79,80};
        arr[14] = new int[]{81,82,83,84,85,86};
        arr[15] = new int[]{87,88};
        arr[16] = new int[]{89,90,91,92,93,94,95,96,97,98,99,100,101,102};
        arr[17] = new int[]{103,104,105,106,107,108,109,110,111,112};
        arr[18] = new int[]{113,114,115,116,117,118};
        
        arr2[0] = "1s";
        arr2[1] = "2s";
        arr2[2] = "2p";
        arr2[3] = "3s";
        arr2[4] = "3p";
        arr2[5] = "4s";
        arr2[6] = "3d";
        arr2[7] = "4p";
        arr2[8] = "5s";
        arr2[9] = "4d";
        arr2[10] = "5p";
        arr2[11] = "6s";
        arr2[12] = "4f";
        arr2[13] = "5d";
        arr2[14] = "6p";
        arr2[15] = "7s";
        arr2[16] = "5f";
        arr2[17] = "6d";
        arr2[18] = "7p";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        numeroA = new javax.swing.JLabel();
        simbolo = new javax.swing.JLabel();
        nombreE = new javax.swing.JLabel();
        masaA = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        slider1 = new javax.swing.JSlider();
        configuracionElectronica = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(128, 128, 131));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/view/img1/home.png"))); // NOI18N
        jLabel2.setText("CONFIGURACIÓN ELECTRONICA");

        numeroA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        numeroA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        simbolo.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        simbolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        nombreE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nombreE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        masaA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        masaA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(numeroA, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(simbolo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(nombreE, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(masaA, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(numeroA, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(simbolo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(masaA, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Elemento Quimico");

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 153), 2));

        jLabel4.setBackground(new java.awt.Color(255, 255, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 255));
        jLabel4.setText("1");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 1, true));

        jLabel5.setBackground(new java.awt.Color(255, 255, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 255));
        jLabel5.setText("2");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 1, true));

        jLabel6.setBackground(new java.awt.Color(255, 255, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 255));
        jLabel6.setText("3");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 1, true));

        jLabel7.setBackground(new java.awt.Color(255, 255, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 255));
        jLabel7.setText("4");
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 1, true));

        jLabel8.setBackground(new java.awt.Color(255, 255, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 255));
        jLabel8.setText("5");
        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 1, true));

        jLabel9.setBackground(new java.awt.Color(255, 255, 0));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 255));
        jLabel9.setText("6");
        jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 1, true));

        jLabel10.setBackground(new java.awt.Color(255, 255, 0));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 255));
        jLabel10.setText("7");
        jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 1, true));

        jLabel11.setBackground(new java.awt.Color(255, 255, 0));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 51));
        jLabel11.setText("s");
        jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 1, true));

        jLabel12.setBackground(new java.awt.Color(255, 255, 0));
        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 51));
        jLabel12.setText("s");
        jLabel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 1, true));

        jLabel13.setBackground(new java.awt.Color(255, 255, 0));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 51));
        jLabel13.setText("s");
        jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 1, true));

        jLabel14.setBackground(new java.awt.Color(255, 255, 0));
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 51));
        jLabel14.setText("s");
        jLabel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 1, true));

        jLabel15.setBackground(new java.awt.Color(255, 255, 0));
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 51));
        jLabel15.setText("s");
        jLabel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 1, true));

        jLabel16.setBackground(new java.awt.Color(255, 255, 0));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 51));
        jLabel16.setText("s");
        jLabel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 1, true));

        jLabel17.setBackground(new java.awt.Color(255, 255, 0));
        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 51));
        jLabel17.setText("s");
        jLabel17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 1, true));

        jLabel19.setBackground(new java.awt.Color(255, 255, 0));
        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 153, 0));
        jLabel19.setText("p");
        jLabel19.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel20.setBackground(new java.awt.Color(255, 255, 0));
        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 153, 0));
        jLabel20.setText("p");
        jLabel20.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel21.setBackground(new java.awt.Color(255, 255, 0));
        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 153, 0));
        jLabel21.setText("p");
        jLabel21.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel22.setBackground(new java.awt.Color(255, 255, 0));
        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 153, 0));
        jLabel22.setText("p");
        jLabel22.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel23.setBackground(new java.awt.Color(255, 255, 0));
        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 153, 0));
        jLabel23.setText("p");
        jLabel23.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel24.setBackground(new java.awt.Color(255, 255, 0));
        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 153, 0));
        jLabel24.setText("p");
        jLabel24.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel27.setBackground(new java.awt.Color(255, 255, 0));
        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 204, 255));
        jLabel27.setText("d");
        jLabel27.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));

        jLabel28.setBackground(new java.awt.Color(255, 255, 0));
        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 204, 255));
        jLabel28.setText("d");
        jLabel28.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));

        jLabel30.setBackground(new java.awt.Color(255, 255, 0));
        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 204, 255));
        jLabel30.setText("d");
        jLabel30.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));

        jLabel31.setBackground(new java.awt.Color(255, 255, 0));
        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 204, 255));
        jLabel31.setText("d");
        jLabel31.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));

        jLabel35.setBackground(new java.awt.Color(255, 255, 0));
        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(204, 0, 204));
        jLabel35.setText("f");
        jLabel35.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 1, true));

        jLabel36.setBackground(new java.awt.Color(255, 255, 0));
        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(204, 0, 204));
        jLabel36.setText("f");
        jLabel36.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 1, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23)
                    .addComponent(jLabel22)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel35)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel36))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel28)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel30)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel31)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel27))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel24))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 153));
        jLabel3.setText("Configuración según el orden de llenado:");

        jLabel41.setBackground(new java.awt.Color(255, 255, 0));
        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 153, 51));
        jLabel41.setText("4s");
        jLabel41.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 1, true));

        jLabel42.setBackground(new java.awt.Color(255, 255, 0));
        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 153, 51));
        jLabel42.setText("5s");
        jLabel42.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 1, true));

        jLabel33.setBackground(new java.awt.Color(255, 255, 0));
        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 204, 255));
        jLabel33.setText("4d");
        jLabel33.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));

        jLabel38.setBackground(new java.awt.Color(255, 255, 0));
        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(204, 0, 204));
        jLabel38.setText("5f");
        jLabel38.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 1, true));

        jLabel47.setBackground(new java.awt.Color(255, 255, 0));
        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 153, 0));
        jLabel47.setText("2p");
        jLabel47.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel48.setBackground(new java.awt.Color(255, 255, 0));
        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 153, 0));
        jLabel48.setText("4p");
        jLabel48.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel44.setBackground(new java.awt.Color(255, 255, 0));
        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 153, 51));
        jLabel44.setText("7s");
        jLabel44.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 1, true));

        jLabel18.setBackground(new java.awt.Color(255, 255, 0));
        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 153, 51));
        jLabel18.setText("1s");
        jLabel18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 1, true));

        jLabel45.setBackground(new java.awt.Color(255, 255, 0));
        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 153, 0));
        jLabel45.setText("6p");
        jLabel45.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel40.setBackground(new java.awt.Color(255, 255, 0));
        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 153, 51));
        jLabel40.setText("3s");
        jLabel40.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 1, true));

        jLabel39.setBackground(new java.awt.Color(255, 255, 0));
        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 153, 51));
        jLabel39.setText("2s");
        jLabel39.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 1, true));

        jLabel29.setBackground(new java.awt.Color(255, 255, 0));
        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 204, 255));
        jLabel29.setText("6d");
        jLabel29.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));

        jLabel37.setBackground(new java.awt.Color(255, 255, 0));
        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(204, 0, 204));
        jLabel37.setText("4f");
        jLabel37.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 1, true));

        jLabel32.setBackground(new java.awt.Color(255, 255, 0));
        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 204, 255));
        jLabel32.setText("3d");
        jLabel32.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));

        jLabel43.setBackground(new java.awt.Color(255, 255, 0));
        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 153, 51));
        jLabel43.setText("6s");
        jLabel43.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 1, true));

        jLabel26.setBackground(new java.awt.Color(255, 255, 0));
        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 153, 0));
        jLabel26.setText("7p");
        jLabel26.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel46.setBackground(new java.awt.Color(255, 255, 0));
        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 153, 0));
        jLabel46.setText("5p");
        jLabel46.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel34.setBackground(new java.awt.Color(255, 255, 0));
        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 204, 255));
        jLabel34.setText("5d");
        jLabel34.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));

        jLabel25.setBackground(new java.awt.Color(255, 255, 0));
        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 153, 0));
        jLabel25.setText("3p");
        jLabel25.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel49.setBackground(new java.awt.Color(255, 255, 0));
        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 153, 51));
        jLabel49.setText("||");
        jLabel49.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 1, true));

        jLabel50.setBackground(new java.awt.Color(255, 255, 0));
        jLabel50.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 153, 51));
        jLabel50.setText("||");
        jLabel50.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 1, true));

        jLabel51.setBackground(new java.awt.Color(255, 255, 0));
        jLabel51.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(0, 153, 51));
        jLabel51.setText("||");
        jLabel51.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 1, true));

        jLabel52.setBackground(new java.awt.Color(255, 255, 0));
        jLabel52.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(0, 153, 51));
        jLabel52.setText("||");
        jLabel52.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 1, true));

        jLabel53.setBackground(new java.awt.Color(255, 255, 0));
        jLabel53.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(0, 153, 51));
        jLabel53.setText("||");
        jLabel53.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 1, true));

        jLabel54.setBackground(new java.awt.Color(255, 255, 0));
        jLabel54.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(0, 153, 51));
        jLabel54.setText("||");
        jLabel54.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 1, true));

        jLabel55.setBackground(new java.awt.Color(255, 255, 0));
        jLabel55.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(0, 153, 51));
        jLabel55.setText("||");
        jLabel55.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 1, true));

        jLabel56.setBackground(new java.awt.Color(255, 255, 0));
        jLabel56.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 153, 0));
        jLabel56.setText("||");
        jLabel56.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel57.setBackground(new java.awt.Color(255, 255, 0));
        jLabel57.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 153, 0));
        jLabel57.setText("||");
        jLabel57.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel58.setBackground(new java.awt.Color(255, 255, 0));
        jLabel58.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 153, 0));
        jLabel58.setText("||");
        jLabel58.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel59.setBackground(new java.awt.Color(255, 255, 0));
        jLabel59.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 153, 0));
        jLabel59.setText("||");
        jLabel59.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel60.setBackground(new java.awt.Color(255, 255, 0));
        jLabel60.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 153, 0));
        jLabel60.setText("||");
        jLabel60.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel61.setBackground(new java.awt.Color(255, 255, 0));
        jLabel61.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 153, 0));
        jLabel61.setText("||");
        jLabel61.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel62.setBackground(new java.awt.Color(255, 255, 0));
        jLabel62.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 153, 0));
        jLabel62.setText("||");
        jLabel62.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel63.setBackground(new java.awt.Color(255, 255, 0));
        jLabel63.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 153, 0));
        jLabel63.setText("||");
        jLabel63.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel64.setBackground(new java.awt.Color(255, 255, 0));
        jLabel64.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 153, 0));
        jLabel64.setText("||");
        jLabel64.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel65.setBackground(new java.awt.Color(255, 255, 0));
        jLabel65.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 153, 0));
        jLabel65.setText("||");
        jLabel65.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel66.setBackground(new java.awt.Color(255, 255, 0));
        jLabel66.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 153, 0));
        jLabel66.setText("||");
        jLabel66.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel67.setBackground(new java.awt.Color(255, 255, 0));
        jLabel67.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 153, 0));
        jLabel67.setText("||");
        jLabel67.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel68.setBackground(new java.awt.Color(255, 255, 0));
        jLabel68.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 153, 0));
        jLabel68.setText("||");
        jLabel68.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel69.setBackground(new java.awt.Color(255, 255, 0));
        jLabel69.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 153, 0));
        jLabel69.setText("||");
        jLabel69.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel70.setBackground(new java.awt.Color(255, 255, 0));
        jLabel70.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 153, 0));
        jLabel70.setText("||");
        jLabel70.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel71.setBackground(new java.awt.Color(255, 255, 0));
        jLabel71.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 153, 0));
        jLabel71.setText("||");
        jLabel71.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel72.setBackground(new java.awt.Color(255, 255, 0));
        jLabel72.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 153, 0));
        jLabel72.setText("||");
        jLabel72.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel73.setBackground(new java.awt.Color(255, 255, 0));
        jLabel73.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 153, 0));
        jLabel73.setText("||");
        jLabel73.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel74.setBackground(new java.awt.Color(255, 255, 0));
        jLabel74.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(0, 204, 255));
        jLabel74.setText("||");
        jLabel74.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));

        jLabel75.setBackground(new java.awt.Color(255, 255, 0));
        jLabel75.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(0, 204, 255));
        jLabel75.setText("||");
        jLabel75.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));

        jLabel76.setBackground(new java.awt.Color(255, 255, 0));
        jLabel76.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(0, 204, 255));
        jLabel76.setText("||");
        jLabel76.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));

        jLabel77.setBackground(new java.awt.Color(255, 255, 0));
        jLabel77.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(0, 204, 255));
        jLabel77.setText("||");
        jLabel77.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));

        jLabel78.setBackground(new java.awt.Color(255, 255, 0));
        jLabel78.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(0, 204, 255));
        jLabel78.setText("||");
        jLabel78.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));

        jLabel79.setBackground(new java.awt.Color(255, 255, 0));
        jLabel79.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(0, 204, 255));
        jLabel79.setText("||");
        jLabel79.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));

        jLabel80.setBackground(new java.awt.Color(255, 255, 0));
        jLabel80.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(0, 204, 255));
        jLabel80.setText("||");
        jLabel80.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));

        jLabel81.setBackground(new java.awt.Color(255, 255, 0));
        jLabel81.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(0, 204, 255));
        jLabel81.setText("||");
        jLabel81.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));

        jLabel82.setBackground(new java.awt.Color(255, 255, 0));
        jLabel82.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(0, 204, 255));
        jLabel82.setText("||");
        jLabel82.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));

        jLabel83.setBackground(new java.awt.Color(255, 255, 0));
        jLabel83.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(0, 204, 255));
        jLabel83.setText("||");
        jLabel83.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));

        jLabel84.setBackground(new java.awt.Color(255, 255, 0));
        jLabel84.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(0, 204, 255));
        jLabel84.setText("||");
        jLabel84.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));

        jLabel85.setBackground(new java.awt.Color(255, 255, 0));
        jLabel85.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(0, 204, 255));
        jLabel85.setText("||");
        jLabel85.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));

        jLabel86.setBackground(new java.awt.Color(255, 255, 0));
        jLabel86.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(0, 204, 255));
        jLabel86.setText("||");
        jLabel86.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));

        jLabel87.setBackground(new java.awt.Color(255, 255, 0));
        jLabel87.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel87.setForeground(new java.awt.Color(0, 204, 255));
        jLabel87.setText("||");
        jLabel87.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));

        jLabel88.setBackground(new java.awt.Color(255, 255, 0));
        jLabel88.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel88.setForeground(new java.awt.Color(0, 204, 255));
        jLabel88.setText("||");
        jLabel88.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));

        jLabel89.setBackground(new java.awt.Color(255, 255, 0));
        jLabel89.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel89.setForeground(new java.awt.Color(0, 204, 255));
        jLabel89.setText("||");
        jLabel89.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));

        jLabel90.setBackground(new java.awt.Color(255, 255, 0));
        jLabel90.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel90.setForeground(new java.awt.Color(0, 204, 255));
        jLabel90.setText("||");
        jLabel90.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));

        jLabel91.setBackground(new java.awt.Color(255, 255, 0));
        jLabel91.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel91.setForeground(new java.awt.Color(0, 204, 255));
        jLabel91.setText("||");
        jLabel91.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));

        jLabel92.setBackground(new java.awt.Color(255, 255, 0));
        jLabel92.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel92.setForeground(new java.awt.Color(0, 204, 255));
        jLabel92.setText("||");
        jLabel92.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));

        jLabel93.setBackground(new java.awt.Color(255, 255, 0));
        jLabel93.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel93.setForeground(new java.awt.Color(0, 204, 255));
        jLabel93.setText("||");
        jLabel93.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));

        jLabel94.setBackground(new java.awt.Color(255, 255, 0));
        jLabel94.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel94.setForeground(new java.awt.Color(204, 0, 204));
        jLabel94.setText("||");
        jLabel94.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 1, true));

        jLabel95.setBackground(new java.awt.Color(255, 255, 0));
        jLabel95.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel95.setForeground(new java.awt.Color(204, 0, 204));
        jLabel95.setText("||");
        jLabel95.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 1, true));

        jLabel96.setBackground(new java.awt.Color(255, 255, 0));
        jLabel96.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel96.setForeground(new java.awt.Color(204, 0, 204));
        jLabel96.setText("||");
        jLabel96.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 1, true));

        jLabel97.setBackground(new java.awt.Color(255, 255, 0));
        jLabel97.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel97.setForeground(new java.awt.Color(204, 0, 204));
        jLabel97.setText("||");
        jLabel97.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 1, true));

        jLabel98.setBackground(new java.awt.Color(255, 255, 0));
        jLabel98.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel98.setForeground(new java.awt.Color(204, 0, 204));
        jLabel98.setText("||");
        jLabel98.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 1, true));

        jLabel99.setBackground(new java.awt.Color(255, 255, 0));
        jLabel99.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel99.setForeground(new java.awt.Color(204, 0, 204));
        jLabel99.setText("||");
        jLabel99.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 1, true));

        jLabel100.setBackground(new java.awt.Color(255, 255, 0));
        jLabel100.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel100.setForeground(new java.awt.Color(204, 0, 204));
        jLabel100.setText("||");
        jLabel100.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 1, true));

        jLabel101.setBackground(new java.awt.Color(255, 255, 0));
        jLabel101.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel101.setForeground(new java.awt.Color(204, 0, 204));
        jLabel101.setText("||");
        jLabel101.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 1, true));

        jLabel102.setBackground(new java.awt.Color(255, 255, 0));
        jLabel102.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel102.setForeground(new java.awt.Color(204, 0, 204));
        jLabel102.setText("||");
        jLabel102.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 1, true));

        jLabel103.setBackground(new java.awt.Color(255, 255, 0));
        jLabel103.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel103.setForeground(new java.awt.Color(204, 0, 204));
        jLabel103.setText("||");
        jLabel103.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 1, true));

        jLabel104.setBackground(new java.awt.Color(255, 255, 0));
        jLabel104.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel104.setForeground(new java.awt.Color(204, 0, 204));
        jLabel104.setText("||");
        jLabel104.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 1, true));

        jLabel105.setBackground(new java.awt.Color(255, 255, 0));
        jLabel105.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel105.setForeground(new java.awt.Color(204, 0, 204));
        jLabel105.setText("||");
        jLabel105.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 1, true));

        jLabel106.setBackground(new java.awt.Color(255, 255, 0));
        jLabel106.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel106.setForeground(new java.awt.Color(204, 0, 204));
        jLabel106.setText("||");
        jLabel106.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 1, true));

        jLabel107.setBackground(new java.awt.Color(255, 255, 0));
        jLabel107.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel107.setForeground(new java.awt.Color(204, 0, 204));
        jLabel107.setText("||");
        jLabel107.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 1, true));

        slider1.setMajorTickSpacing(1);
        slider1.setMaximum(118);
        slider1.setMinimum(1);
        slider1.setOrientation(javax.swing.JSlider.VERTICAL);
        slider1.setPaintTicks(true);
        slider1.setValue(1);
        slider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider1StateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(slider1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(configuracionElectronica)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(67, 67, 67)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel39)
                                            .addComponent(jLabel40)
                                            .addComponent(jLabel41)
                                            .addComponent(jLabel42)
                                            .addComponent(jLabel43)
                                            .addComponent(jLabel44))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel49)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel50)
                                                    .addComponent(jLabel51)
                                                    .addComponent(jLabel52)
                                                    .addComponent(jLabel53)
                                                    .addComponent(jLabel54)
                                                    .addComponent(jLabel55))
                                                .addGap(39, 39, 39)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel47)
                                                    .addComponent(jLabel26)
                                                    .addComponent(jLabel25)
                                                    .addComponent(jLabel48)
                                                    .addComponent(jLabel46)
                                                    .addComponent(jLabel45))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel56)
                                                    .addComponent(jLabel61)
                                                    .addComponent(jLabel57)
                                                    .addComponent(jLabel58)
                                                    .addComponent(jLabel59)
                                                    .addComponent(jLabel60))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel62)
                                                    .addComponent(jLabel67)
                                                    .addComponent(jLabel63)
                                                    .addComponent(jLabel64)
                                                    .addComponent(jLabel65)
                                                    .addComponent(jLabel66))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel68)
                                                    .addComponent(jLabel73)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel69)
                                                            .addComponent(jLabel70)
                                                            .addComponent(jLabel71)
                                                            .addComponent(jLabel72))
                                                        .addGap(38, 38, 38)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel32)
                                                            .addComponent(jLabel29)
                                                            .addComponent(jLabel33)
                                                            .addComponent(jLabel34))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel74)
                                                            .addComponent(jLabel77)
                                                            .addComponent(jLabel75)
                                                            .addComponent(jLabel76))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel78)
                                                            .addComponent(jLabel81)
                                                            .addComponent(jLabel79)
                                                            .addComponent(jLabel80))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel82)
                                                            .addComponent(jLabel85)
                                                            .addComponent(jLabel83)
                                                            .addComponent(jLabel84))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel86)
                                                            .addComponent(jLabel89)
                                                            .addComponent(jLabel87)
                                                            .addComponent(jLabel88))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel90)
                                                            .addComponent(jLabel93)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(jLabel91)
                                                                    .addComponent(jLabel92))
                                                                .addGap(38, 38, 38)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(jLabel37)
                                                                    .addComponent(jLabel38))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(jLabel94)
                                                                    .addComponent(jLabel95))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(jLabel96)
                                                                    .addComponent(jLabel97))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(jLabel98)
                                                                    .addComponent(jLabel99))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(jLabel100)
                                                                    .addComponent(jLabel101))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(jLabel102)
                                                                    .addComponent(jLabel103))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(jLabel104)
                                                                    .addComponent(jLabel105))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(jLabel106)
                                                                    .addComponent(jLabel107)))))))))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(199, 199, 199))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(137, 137, 137))))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(slider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(configuracionElectronica))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel49)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel50)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel51)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel52)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel53)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel54)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel55))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel47)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel25)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel48)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel46)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel45)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel26))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel56)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel57)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel58)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel59)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel60)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel61))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel62)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel63)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel64)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel65)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel66)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel67))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel68)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel69)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel70)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel71)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel72))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel32)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel33)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel34)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel29))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel74)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel75)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel76)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel77))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel78)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel79)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel80)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel81))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel82)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel83)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel84)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel85))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel86)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel87)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel88)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel89))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel90)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel91)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel92))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel37)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel38))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel94)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel95))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel96)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel97))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel98)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel99))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel100)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel101))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel102)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel103))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel104)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel105))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel106)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel107)))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel93)))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel73))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel39)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel40)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel41)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel42)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel43)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel44)))))
                .addContainerGap(334, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void printElement(int position){
        Conectar conectar =  new Conectar();
        // retorna el objeto de la conexion 
        Connection con = conectar.getConnection();
        try {
            //retorna el objeto para hacer la consulta 
            Statement sentencia = con.createStatement();
            String sql = "SELECT * FROM tablaperiodica WHERE id = " + position;
            ResultSet response = sentencia.executeQuery(sql);
            Boolean flag = false;
            while(response.next()){
                simbolo.setText(response.getString(5));
                nombreE.setText(response.getString(2));
                numeroA.setText(String.valueOf(response.getInt(4)));
                masaA.setText(String.valueOf(response.getDouble(3)));
                flag = (!flag)?true:flag;
            }
            if(!flag){
                System.out.println("No se encontro el elemento");
            }
        } catch (SQLException ex) {
            Logger.getLogger(pnlCuatro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void electronicConfiguration(int position){
        String output = "";
        //acceder a los elementos del array
        boolean flag = false;
        // Para saber  cuantos electrones hay en cada iteración
        int value = 0;
        for (int i = 0; i < arr.length; i++){
            for(int j=0;j<arr[i].length;j++){
                value = j+1;
                if(arr[i][j] == position){
                    flag = true;
                    break;
                }
            }
            // Concatena hasta llegar a la posicion 
            output += arr2[i] + value + " ";
            if(flag) break;
        }
        configuracionElectronica.setText(output);
    }
    
    private void slider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider1StateChanged
        // Obtenemos la posicion en el Slider
        int position = Integer.valueOf(slider1.getValue());
        
        // Imprimir el elemento de la posicion
        printElement(position);
        
        // Imprimir la configuración electronica
        electronicConfiguration(position);
    }//GEN-LAST:event_slider1StateChanged

    private int arr[][] = new int[19][];
    private String arr2[] = new String[19];
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel configuracionElectronica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel masaA;
    private javax.swing.JLabel nombreE;
    private javax.swing.JLabel numeroA;
    private javax.swing.JLabel simbolo;
    private javax.swing.JSlider slider1;
    // End of variables declaration//GEN-END:variables
}
